# =============================================================================
# Terraform Backend Configuration - S3 + DynamoDB
# =============================================================================
# Auto-generated by setup-aws-storage.sh
# This stores Terraform state in S3 with locking via DynamoDB
# =============================================================================

terraform {
  backend "s3" {
    bucket         = "devops-tfstate-632008729195"
    key            = "devops-testing-app/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "devops-tfstate-lock"
  }
}
